language: java
jdk:
- oraclejdk7
before_install:
  - echo "MAVEN_OPTS='-Xmx2g -XX:MaxPermSize=1024m'" > ~/.mavenrc
script:
  - ls ~/.ssh
  - cat /etc/init.d/xvfb
  - which firefox
after_success:
  - echo "done done"
